name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    # https://github.com/devcontainers/ci/issues/191
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - id: format
        # https://github.com/devcontainers/ci/issues/235
        run: |
          prefix="ghcr.io/${{ github.repository }}:"

          tags=$(echo "${{ steps.meta.outputs.tags }}" | sed -e "s#${prefix}##g")
          tags=$(echo "${tags}" | tr "\n" ",")
          tags=$(echo "${tags}" | sed "s/,*$//")

          echo "tags=${tags}" >> $GITHUB_OUTPUT
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.3
        with:
          subFolder: src
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: |
            ghcr.io/${{ github.repository }}
            ghcr.io/${{ github.repository }}:main
          platform: linux/amd64,linux/arm64
          imageTag: ${{ steps.format.outputs.tags }}
          push: always
